-- MySQL Script generated by MySQL Workbench
-- Fri Mar  3 20:14:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudiante` (
  `idestudiante` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(200) NULL,
  `apellidopaterno` VARCHAR(200) NULL,
  `ApellidoMaterno` VARCHAR(200) NULL,
  `DNI` VARCHAR(8) NULL,
  `telefono` VARCHAR(11) NULL,
  PRIMARY KEY (`idestudiante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grado` (
  `idgrado` INT NOT NULL,
  `seccion` VARCHAR(45) NULL,
  `totalestudiantes` VARCHAR(45) NULL,
  PRIMARY KEY (`idgrado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`asistencia` (
  `idasistencia` INT NOT NULL AUTO_INCREMENT,
  `justificado` VARCHAR(2) NULL,
  `injustificado` VARCHAR(2) NULL,
  `tardanza` VARCHAR(2) NULL,
  `presente` VARCHAR(2) NULL,
  `estudiante_idestudiante` INT NOT NULL,
  PRIMARY KEY (`idasistencia`),
  INDEX `fk_asistencia_estudiante1_idx` (`estudiante_idestudiante` ASC) ,
  CONSTRAINT `fk_asistencia_estudiante1`
    FOREIGN KEY (`estudiante_idestudiante`)
    REFERENCES `mydb`.`estudiante` (`idestudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `nombrecurso` VARCHAR(45) NULL,
  PRIMARY KEY (`idcurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personal` (
  `idpersonal` INT NOT NULL,
  `Nombres` VARCHAR(45) NULL,
  `ApellidoPaterno` VARCHAR(45) NULL,
  `ApellidoMaterno` VARCHAR(45) NULL,
  `Usuario` VARCHAR(10) NULL,
  `Clave` VARCHAR(8) NULL,
  `curso_idcurso` INT NOT NULL,
  PRIMARY KEY (`idpersonal`),
  INDEX `fk_personal_curso1_idx` (`curso_idcurso` ASC) ,
  CONSTRAINT `fk_personal_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `mydb`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuario` (
  `idtipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(10) NULL,
  `personal_idpersonal` INT NOT NULL,
  PRIMARY KEY (`idtipo_usuario`),
  INDEX `fk_tipo_usuario_personal1_idx` (`personal_idpersonal` ASC) ,
  CONSTRAINT `fk_tipo_usuario_personal1`
    FOREIGN KEY (`personal_idpersonal`)
    REFERENCES `mydb`.`personal` (`idpersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notas` (
  `idNotas` INT NOT NULL AUTO_INCREMENT,
  `semestre1` DECIMAL(4,2) NULL,
  `semestre2` DECIMAL(4,2) NULL,
  `semestre3` DECIMAL(4,2) NULL,
  `promedio` DECIMAL(4,2) NULL,
  `curso_idcurso` INT NOT NULL,
  `estudiante_idestudiante` INT NOT NULL,
  PRIMARY KEY (`idNotas`),
  INDEX `fk_Notas_curso1_idx` (`curso_idcurso` ASC) ,
  INDEX `fk_Notas_estudiante1_idx` (`estudiante_idestudiante` ASC) ,
  CONSTRAINT `fk_Notas_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `mydb`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notas_estudiante1`
    FOREIGN KEY (`estudiante_idestudiante`)
    REFERENCES `mydb`.`estudiante` (`idestudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notas_periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notas_periodo` (
  `idtable1` INT NOT NULL,
  `nota_semestre1` VARCHAR(45) NULL,
  `nota_semestre2` VARCHAR(45) NULL,
  `nota_semestre3` VARCHAR(45) NULL,
  `PromedioAnual` VARCHAR(45) NULL,
  `Notas_idNotas` INT NOT NULL,
  PRIMARY KEY (`idtable1`),
  INDEX `fk_notas_periodo_Notas_idx` (`Notas_idNotas` ASC) ,
  CONSTRAINT `fk_notas_periodo_Notas`
    FOREIGN KEY (`Notas_idNotas`)
    REFERENCES `mydb`.`Notas` (`idNotas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`institucion` (
  `idinstitucion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `nivel` VARCHAR(45) NULL,
  `codigo modular` VARCHAR(45) NULL,
  PRIMARY KEY (`idinstitucion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conduccion_descripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conduccion_descripcion` (
  `idconduccion_descripcion` INT NOT NULL AUTO_INCREMENT,
  `id_estudiante` VARCHAR(45) NULL,
  `id_persona` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `periodo` VARCHAR(45) NULL,
  `estudiante_idestudiante` INT NOT NULL,
  PRIMARY KEY (`idconduccion_descripcion`),
  INDEX `fk_conduccion_descripcion_estudiante1_idx` (`estudiante_idestudiante` ASC) ,
  CONSTRAINT `fk_conduccion_descripcion_estudiante1`
    FOREIGN KEY (`estudiante_idestudiante`)
    REFERENCES `mydb`.`estudiante` (`idestudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grado_estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grado_estudiantes` (
  `idgrado_estudiantes` INT NOT NULL AUTO_INCREMENT,
  `grado_idgrado` INT NOT NULL,
  `estudiante_idestudiante` INT NOT NULL,
  PRIMARY KEY (`idgrado_estudiantes`),
  INDEX `fk_grado_estudiantes_grado1_idx` (`grado_idgrado` ASC) ,
  INDEX `fk_grado_estudiantes_estudiante1_idx` (`estudiante_idestudiante` ASC) ,
  CONSTRAINT `fk_grado_estudiantes_grado1`
    FOREIGN KEY (`grado_idgrado`)
    REFERENCES `mydb`.`grado` (`idgrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grado_estudiantes_estudiante1`
    FOREIGN KEY (`estudiante_idestudiante`)
    REFERENCES `mydb`.`estudiante` (`idestudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
